version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    target-branch: "dev"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0

  - package-ecosystem: "npm"
    directory: "/extensions/vscode"
    target-branch: "dev"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0

  - package-ecosystem: "cargo"
    directory: "/extensions/zed"
    target-branch: "dev"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0

  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "dev"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0
