name: Check and Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_call:
jobs:
  check-path-server:
    name: Format and Clippy Path Server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Run Format Check
        run: cargo fmt --all -- --check

      - name: Run Clippy
        run: cargo clippy -- -D warnings

  check-zed-extension:
    name: Format and Clippy Zed Extension
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Run Format Check
        working-directory: ./extensions/zed
        run: cargo fmt --all -- --check

      - name: Run Clippy
        working-directory: ./extensions/zed
        run: cargo clippy -- -D warnings

  check-vscode-extension:
    name: Check VSCode Extension
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        working-directory: ./extensions/vscode
        run: npm install

      - name: Check types for VS Code Extension
        working-directory: ./extensions/vscode
        run: npm run check-types
      - name: Lint VS Code Extension
        working-directory: ./extensions/vscode
        run: npm run lint

  # Test Path Server on 3 platforms
  test-path-server:
    name: Test Path Server on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Run Tests
        run: cargo test
